Parameters:
  VpcId:
    Description: Enter the VpcId
    Type: "AWS::EC2::VPC::Id"
  SubnetId:
    Description: Enter the SubnetId
    Type: AWS::EC2::Subnet::Id
Mappings:
  RegionMap:
    us-west-1:
      AMALINUX: "ami-0b2d8d1abb76a53d8"
    eu-central-1:
      AMALINUX: "ami-0d4c3eabb9e72650a"

Resources:
  SG:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
       VpcId: !Ref VpcId
       GroupDescription: !Sub "${AWS::StackName} Security group"
       SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  EC2:
    Type: "AWS::EC2::Instance"
    CreationPolicy:
      ResourceSignal:
        Count: "1"
        Timeout: PT15M
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMALINUX] # Dynamic mapping + Pseudo Parameter
      InstanceType: "t2.micro"
      SubnetId: !Ref SubnetId
      Tags:
        - 
          Key: Name
          Value: !Sub "${AWS::StackName} Instance"
      SecurityGroupIds:
        - !Ref SG
      UserData:
        "Fn::Base64":
          !Sub |
            #!/bin/bash
            yum install httpd php mysql php-mysql -y
            yum update -y
            chkconfig httpd on
            service httpd start
            cd /var/www/html
            wget https://www.adminer.org/latest.php
            mv latest.php index.php
            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource EC2 --region ${AWS::Region}
Outputs:
  wproot:
    Description: Access URL
    Value: !Join ["", ["http://", !GetAtt EC2.PublicIp, "/index.php"]]