Parameters:
  VpcId:
    Description: Enter the VpcId
    Type: "AWS::EC2::VPC::Id"
  SubnetId:
    Description: Enter the SubnetId
    Type: AWS::EC2::Subnet::Id
  AdminUserName: 
    Type: String
    Description: RQM user name
  AdminUserPassword: 
    Type: String
    NoEcho: true
    MinLength: 1
    MaxLength: 41
    AllowedPattern: ^[a-zA-Z0-9]*$
    Description: RQM user password
    
Mappings:
  RegionMap:
    us-west-1:
      AMALINUX: "ami-0b2d8d1abb76a53d8"
    eu-central-1:
      AMALINUX: "ami-0d4c3eabb9e72650a"
    
Resources:
  Role:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM"

  IAMInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: /
      Roles:
        - !Ref Role    

  SG:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
       VpcId: !Ref VpcId
       GroupDescription: !Sub "${AWS::StackName} Security group"
       SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5672
          ToPort: 5672
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 15672
          ToPort: 15672
          CidrIp: 0.0.0.0/0
  EC2Master:
    Type: "AWS::EC2::Instance"
    CreationPolicy:
      ResourceSignal:
        Count: "1"
        Timeout: PT15M
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMALINUX] # Dynamic mapping + Pseudo Parameter
      InstanceType: "t2.micro"
      SubnetId: !Ref SubnetId
      Tags:
        - 
          Key: Name
          Value: !Sub "${AWS::StackName} Master Instance"
      SecurityGroupIds:
        - !Ref SG
      IamInstanceProfile: !Ref IAMInstanceProfile
      UserData:
        "Fn::Base64":
          !Sub |
            #!/bin/bash
            
            yum update -y

            # Installing RMQ-Server

            # import the new PackageCloud key that will be used starting December 1st, 2018 (GMT)
            rpm --import https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey

            # import the old PackageCloud key that will be discontinued on December 1st, 2018 (GMT)
            rpm --import https://packagecloud.io/gpg.key

            curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | sudo bash

            curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash

            yum install rabbitmq-server -y
            
            service rabbitmq-server start

            chkconfig rabbitmq-server on
            
            rabbitmq-plugins enable rabbitmq_management
            
            rabbitmqctl add_user ${AdminUserName} ${AdminUserPassword}

            rabbitmqctl set_user_tags ${AdminUserName} administrator

            rabbitmqctl set_permissions -p / ${AdminUserName} .* .* .*

            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource EC2Master --region ${AWS::Region}
            
Outputs:
    MasterNodeManagementPlugin:
        Description: Master node management url
        Value: 
            !Sub
              - http://${PrivateIp}:15672
              - PrivateIp: !GetAtt EC2Master.PrivateIp